version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell

linters-settings:
  gocritic:
    disabled-checks:
      - commentFormatting

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 3m
