package generator

import (
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// MappingEntry beschreibt einen generierten Registry-Eintrag.
type MappingEntry struct {
	Name      string
	JSONLFile string
	TypeName  string
	Indices   []string
}

// DeriveIndices leitet Index-Spalten per Konvention ab: alle Felder mit
// Suffix "ID" außer dem Primärschlüssel "_key", sortiert.
func DeriveIndices(schema *Schema) []string {
	var indices []string
	for name := range schema.Fields {
		if name == "_key" {
			continue
		}
		if strings.HasSuffix(name, "ID") {
			indices = append(indices, name)
		}
	}
	sort.Strings(indices)
	return indices
}

// WriteMappingsFile schreibt die generierte Registry-Datei (gofmt-formatiert).
func WriteMappingsFile(outputPath, packageName string, entries []MappingEntry) error {
	var b strings.Builder
	b.WriteString("// Code generated by sde-schema-gen. DO NOT EDIT.\n\n")
	b.WriteString("package " + packageName + "\n\n")
	b.WriteString("import (\n\t\"reflect\"\n\n\t\"github.com/Sternrassler/eve-sde/internal/schema/types\"\n)\n\n")
	b.WriteString("// Mappings is the generated registry of all JSONL datasets to import.\n")
	b.WriteString("var Mappings = []SchemaMapping{\n")
	for _, e := range entries {
		idx := "nil"
		if len(e.Indices) > 0 {
			quoted := make([]string, len(e.Indices))
			for i, s := range e.Indices {
				quoted[i] = fmt.Sprintf("%q", s)
			}
			idx = "[]string{" + strings.Join(quoted, ", ") + "}"
		}
		fmt.Fprintf(&b, "\t{Name: %q, JSONLFile: %q, StructType: reflect.TypeOf(types.%s{}), Indices: %s},\n",
			e.Name, e.JSONLFile, e.TypeName, idx)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format generated mappings: %w", err)
	}
	return os.WriteFile(outputPath, formatted, 0644)
}
