// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: agentsInSpace.jsonl

package types

// AgentsInSpace represents the schema for agentsInSpace.jsonl
type AgentsInSpace struct {
	Key int64 `json:"_key"`
	DungeonID int64 `json:"dungeonID"`
	SolarSystemID int64 `json:"solarSystemID"`
	SpawnPointID int64 `json:"spawnPointID"`
	TypeID int64 `json:"typeID"`
}
