// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: agentTypes.jsonl

package types

// AgentTypes represents the schema for agentTypes.jsonl
type AgentTypes struct {
	Key int64 `json:"_key,omitempty"`
	Name string `json:"name,omitempty"`
}
