// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: agentsInSpace.jsonl

package types

// AgentsInSpace represents the schema for agentsInSpace.jsonl
type AgentsInSpace struct {
	Key int64 `json:"_key,omitempty"`
	DungeonID int64 `json:"dungeonID,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	SpawnPointID int64 `json:"spawnPointID,omitempty"`
	TypeID int64 `json:"typeID,omitempty"`
}
