// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: ancestries.jsonl

package types

// Ancestries represents the schema for ancestries.jsonl
type Ancestries struct {
	Key int64 `json:"_key"`
	BloodlineID int64 `json:"bloodlineID,omitempty"`
	Charisma int64 `json:"charisma,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	Intelligence int64 `json:"intelligence,omitempty"`
	Memory int64 `json:"memory,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Perception int64 `json:"perception,omitempty"`
	ShortDescription string `json:"shortDescription,omitempty"`
	Willpower int64 `json:"willpower,omitempty"`
}
