// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: ancestries.jsonl

package types

// Ancestries represents the schema for ancestries.jsonl
type Ancestries struct {
	Key int64 `json:"_key"`
	BloodlineID int64 `json:"bloodlineID"`
	Charisma int64 `json:"charisma"`
	Description LocalizedText `json:"description"`
	IconID int64 `json:"iconID,omitempty"`
	Intelligence int64 `json:"intelligence"`
	Memory int64 `json:"memory"`
	Name LocalizedText `json:"name"`
	Perception int64 `json:"perception"`
	ShortDescription string `json:"shortDescription,omitempty"`
	Willpower int64 `json:"willpower"`
}
