// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: archetypes.jsonl

package types

// Archetypes represents the schema for archetypes.jsonl
type Archetypes struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description"`
	Title LocalizedText `json:"title,omitempty"`
}
