// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: bloodlines.jsonl

package types

// Bloodlines represents the schema for bloodlines.jsonl
type Bloodlines struct {
	Key int64 `json:"_key"`
	Charisma int64 `json:"charisma,omitempty"`
	CorporationID int64 `json:"corporationID,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	Intelligence int64 `json:"intelligence,omitempty"`
	Memory int64 `json:"memory,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Perception int64 `json:"perception,omitempty"`
	RaceID int64 `json:"raceID,omitempty"`
	Willpower int64 `json:"willpower,omitempty"`
}
