// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: bloodlines.jsonl

package types

// Bloodlines represents the schema for bloodlines.jsonl
type Bloodlines struct {
	Key int64 `json:"_key"`
	Charisma int64 `json:"charisma"`
	CorporationID int64 `json:"corporationID"`
	Description LocalizedText `json:"description"`
	IconID int64 `json:"iconID,omitempty"`
	Intelligence int64 `json:"intelligence"`
	Memory int64 `json:"memory"`
	Name LocalizedText `json:"name"`
	Perception int64 `json:"perception"`
	RaceID int64 `json:"raceID"`
	Willpower int64 `json:"willpower"`
}
