// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: blueprints.jsonl

package types

// Blueprints represents the schema for blueprints.jsonl
type Blueprints struct {
	Key int64 `json:"_key"`
	Activities map[string]interface{} `json:"activities"`
	BlueprintTypeID int64 `json:"blueprintTypeID"`
	MaxProductionLimit int64 `json:"maxProductionLimit"`
}
