// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: categories.jsonl

package types

// Categories represents the schema for categories.jsonl
type Categories struct {
	Key int64 `json:"_key"`
	IconID int64 `json:"iconID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Published bool `json:"published,omitempty"`
}
