// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: certificates.jsonl

package types

// Certificates represents the schema for certificates.jsonl
type Certificates struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description"`
	GroupID int64 `json:"groupID"`
	Name LocalizedText `json:"name"`
	RecommendedFor []int64 `json:"recommendedFor,omitempty"`
	SkillTypes []map[string]interface{} `json:"skillTypes"`
}
