// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: characterAttributes.jsonl

package types

// CharacterAttributes represents the schema for characterAttributes.jsonl
type CharacterAttributes struct {
	Key int64 `json:"_key,omitempty"`
	Description string `json:"description,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Notes string `json:"notes,omitempty"`
	ShortDescription string `json:"shortDescription,omitempty"`
}
