// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: characterAttributes.jsonl

package types

// CharacterAttributes represents the schema for characterAttributes.jsonl
type CharacterAttributes struct {
	Key int64 `json:"_key"`
	Description string `json:"description"`
	IconID int64 `json:"iconID"`
	Name LocalizedText `json:"name"`
	Notes string `json:"notes"`
	ShortDescription string `json:"shortDescription"`
}
