// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: cloneGrades.jsonl

package types

// CloneGrades represents the schema for cloneGrades.jsonl
type CloneGrades struct {
	Key int64 `json:"_key"`
	Name string `json:"name"`
	Skills []map[string]interface{} `json:"skills"`
}
