// Code generated by sde-schema-gen
// DO NOT EDIT manually

package types

// LocalizedText repräsentiert mehrsprachige Texte im EVE SDE
type LocalizedText struct {
	De string `json:"de,omitempty"`
	En string `json:"en"`
	Es string `json:"es,omitempty"`
	Fr string `json:"fr,omitempty"`
	Ja string `json:"ja,omitempty"`
	Ko string `json:"ko,omitempty"`
	Ru string `json:"ru,omitempty"`
	Zh string `json:"zh,omitempty"`
}
