// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: compressibleTypes.jsonl

package types

// CompressibleTypes represents the schema for compressibleTypes.jsonl
type CompressibleTypes struct {
	Key int64 `json:"_key"`
	CompressedTypeID int64 `json:"compressedTypeID"`
}
