// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: controlTowerResources.jsonl

package types

// ControlTowerResources represents the schema for controlTowerResources.jsonl
type ControlTowerResources struct {
	Key int64 `json:"_key,omitempty"`
	Resources []map[string]interface{} `json:"resources,omitempty"`
}
