// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: contrabandTypes.jsonl

package types

// ContrabandTypes represents the schema for contrabandTypes.jsonl
type ContrabandTypes struct {
	Key int64 `json:"_key,omitempty"`
	Factions []map[string]interface{} `json:"factions,omitempty"`
}
