// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: corporationActivities.jsonl

package types

// CorporationActivities represents the schema for corporationActivities.jsonl
type CorporationActivities struct {
	Key int64 `json:"_key,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
}
