// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dbuffCollections.jsonl

package types

// DbuffCollections represents the schema for dbuffCollections.jsonl
type DbuffCollections struct {
	Key int64 `json:"_key"`
	AggregateMode string `json:"aggregateMode,omitempty"`
	DeveloperDescription string `json:"developerDescription,omitempty"`
	DisplayName LocalizedText `json:"displayName,omitempty"`
	ItemModifiers []map[string]interface{} `json:"itemModifiers,omitempty"`
	LocationGroupModifiers []map[string]interface{} `json:"locationGroupModifiers,omitempty"`
	LocationModifiers []map[string]interface{} `json:"locationModifiers,omitempty"`
	LocationRequiredSkillModifiers []map[string]interface{} `json:"locationRequiredSkillModifiers,omitempty"`
	OperationName string `json:"operationName,omitempty"`
	ShowOutputValueInUI string `json:"showOutputValueInUI,omitempty"`
}
