// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dogmaAttributes.jsonl

package types

// DogmaAttributes represents the schema for dogmaAttributes.jsonl
type DogmaAttributes struct {
	Key int64 `json:"_key,omitempty"`
	AttributeCategoryID int64 `json:"attributeCategoryID,omitempty"`
	ChargeRechargeTimeID int64 `json:"chargeRechargeTimeID,omitempty"`
	DataType int64 `json:"dataType,omitempty"`
	DefaultValue int64 `json:"defaultValue,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayName LocalizedText `json:"displayName,omitempty"`
	DisplayWhenZero bool `json:"displayWhenZero,omitempty"`
	HighIsGood bool `json:"highIsGood,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	MaxAttributeID int64 `json:"maxAttributeID,omitempty"`
	MinAttributeID int64 `json:"minAttributeID,omitempty"`
	Name string `json:"name,omitempty"`
	Published bool `json:"published,omitempty"`
	Stackable bool `json:"stackable,omitempty"`
	TooltipDescription LocalizedText `json:"tooltipDescription,omitempty"`
	TooltipTitle LocalizedText `json:"tooltipTitle,omitempty"`
	UnitID int64 `json:"unitID,omitempty"`
}
