// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dogmaEffects.jsonl

package types

// DogmaEffects represents the schema for dogmaEffects.jsonl
type DogmaEffects struct {
	Key int64 `json:"_key,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	DisallowAutoRepeat bool `json:"disallowAutoRepeat,omitempty"`
	DischargeAttributeID int64 `json:"dischargeAttributeID,omitempty"`
	DisplayName LocalizedText `json:"displayName,omitempty"`
	Distribution int64 `json:"distribution,omitempty"`
	DurationAttributeID int64 `json:"durationAttributeID,omitempty"`
	EffectCategoryID int64 `json:"effectCategoryID,omitempty"`
	ElectronicChance bool `json:"electronicChance,omitempty"`
	FalloffAttributeID int64 `json:"falloffAttributeID,omitempty"`
	Guid string `json:"guid,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	IsAssistance bool `json:"isAssistance,omitempty"`
	IsOffensive bool `json:"isOffensive,omitempty"`
	IsWarpSafe bool `json:"isWarpSafe,omitempty"`
	ModifierInfo []map[string]interface{} `json:"modifierInfo,omitempty"`
	Name string `json:"name,omitempty"`
	PropulsionChance bool `json:"propulsionChance,omitempty"`
	Published bool `json:"published,omitempty"`
	RangeAttributeID int64 `json:"rangeAttributeID,omitempty"`
	RangeChance bool `json:"rangeChance,omitempty"`
	TrackingSpeedAttributeID int64 `json:"trackingSpeedAttributeID,omitempty"`
}
