// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dogmaAttributeCategories.jsonl

package types

// DogmaAttributeCategories represents the schema for dogmaAttributeCategories.jsonl
type DogmaAttributeCategories struct {
	Key int64 `json:"_key"`
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
}
