// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dogmaUnits.jsonl

package types

// DogmaUnits represents the schema for dogmaUnits.jsonl
type DogmaUnits struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description,omitempty"`
	DisplayName LocalizedText `json:"displayName,omitempty"`
	Name string `json:"name,omitempty"`
}
