// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dungeons.jsonl

package types

// Dungeons represents the schema for dungeons.jsonl
type Dungeons struct {
	Key int64 `json:"_key"`
	AllowedShipsList []int64 `json:"allowedShipsList,omitempty"`
	ArchetypeID int64 `json:"archetypeID"`
	Description LocalizedText `json:"description,omitempty"`
	FactionID int64 `json:"factionID,omitempty"`
	GameplayDescription LocalizedText `json:"gameplayDescription,omitempty"`
	Name LocalizedText `json:"name"`
}
