// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: dynamicItemAttributes.jsonl

package types

// DynamicItemAttributes represents the schema for dynamicItemAttributes.jsonl
type DynamicItemAttributes struct {
	Key int64 `json:"_key"`
	AttributeIDs []map[string]interface{} `json:"attributeIDs,omitempty"`
	InputOutputMapping []map[string]interface{} `json:"inputOutputMapping,omitempty"`
}
