// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: factions.jsonl

package types

// Factions represents the schema for factions.jsonl
type Factions struct {
	Key int64 `json:"_key"`
	CorporationID int64 `json:"corporationID,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	FlatLogo string `json:"flatLogo,omitempty"`
	FlatLogoWithName string `json:"flatLogoWithName,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	MemberRaces []int64 `json:"memberRaces,omitempty"`
	MilitiaCorporationID int64 `json:"militiaCorporationID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	ShortDescription LocalizedText `json:"shortDescription,omitempty"`
	SizeFactor int64 `json:"sizeFactor,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	UniqueName bool `json:"uniqueName,omitempty"`
}
