// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: freelanceJobSchemas.jsonl

package types

// FreelanceJobSchemas represents the schema for freelanceJobSchemas.jsonl
type FreelanceJobSchemas struct {
	Key int64 `json:"_key"`
	Value []map[string]interface{} `json:"_value"`
}
