// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: graphics.jsonl

package types

// Graphics represents the schema for graphics.jsonl
type Graphics struct {
	Key int64 `json:"_key,omitempty"`
	GraphicFile string `json:"graphicFile,omitempty"`
	IconFolder string `json:"iconFolder,omitempty"`
	SofFactionName string `json:"sofFactionName,omitempty"`
	SofHullName string `json:"sofHullName,omitempty"`
	SofRaceName string `json:"sofRaceName,omitempty"`
}
