// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: groups.jsonl

package types

// Groups represents the schema for groups.jsonl
type Groups struct {
	Key int64 `json:"_key"`
	Anchorable bool `json:"anchorable"`
	Anchored bool `json:"anchored"`
	CategoryID int64 `json:"categoryID"`
	FittableNonSingleton bool `json:"fittableNonSingleton"`
	IconID int64 `json:"iconID,omitempty"`
	Name LocalizedText `json:"name"`
	Published bool `json:"published"`
	UseBasePrice bool `json:"useBasePrice"`
}
