// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: groups.jsonl

package types

// Groups represents the schema for groups.jsonl
type Groups struct {
	Key int64 `json:"_key"`
	Anchorable bool `json:"anchorable,omitempty"`
	Anchored bool `json:"anchored,omitempty"`
	CategoryID int64 `json:"categoryID,omitempty"`
	FittableNonSingleton bool `json:"fittableNonSingleton,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Published bool `json:"published,omitempty"`
	UseBasePrice bool `json:"useBasePrice,omitempty"`
}
