// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: icons.jsonl

package types

// Icons represents the schema for icons.jsonl
type Icons struct {
	Key int64 `json:"_key"`
	IconFile string `json:"iconFile,omitempty"`
}
