// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: landmarks.jsonl

package types

// Landmarks represents the schema for landmarks.jsonl
type Landmarks struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	LocationID int64 `json:"locationID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Position map[string]interface{} `json:"position,omitempty"`
}
