// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapMoons.jsonl

package types

// MapMoons represents the schema for mapMoons.jsonl
type MapMoons struct {
	Key int64 `json:"_key"`
	Attributes map[string]interface{} `json:"attributes"`
	CelestialIndex int64 `json:"celestialIndex"`
	NpcStationIDs []int64 `json:"npcStationIDs,omitempty"`
	OrbitID int64 `json:"orbitID"`
	OrbitIndex int64 `json:"orbitIndex"`
	Position map[string]interface{} `json:"position"`
	Radius int64 `json:"radius"`
	SolarSystemID int64 `json:"solarSystemID"`
	Statistics map[string]interface{} `json:"statistics,omitempty"`
	TypeID int64 `json:"typeID"`
	UniqueName LocalizedText `json:"uniqueName,omitempty"`
}
