// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapAsteroidBelts.jsonl

package types

// MapAsteroidBelts represents the schema for mapAsteroidBelts.jsonl
type MapAsteroidBelts struct {
	Key int64 `json:"_key"`
	CelestialIndex int64 `json:"celestialIndex"`
	OrbitID int64 `json:"orbitID"`
	OrbitIndex int64 `json:"orbitIndex"`
	Position map[string]interface{} `json:"position"`
	Radius float64 `json:"radius,omitempty"`
	SolarSystemID int64 `json:"solarSystemID"`
	Statistics map[string]interface{} `json:"statistics,omitempty"`
	TypeID int64 `json:"typeID"`
	UniqueName LocalizedText `json:"uniqueName,omitempty"`
}
