// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapConstellations.jsonl

package types

// MapConstellations represents the schema for mapConstellations.jsonl
type MapConstellations struct {
	Key int64 `json:"_key,omitempty"`
	FactionID int64 `json:"factionID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Position map[string]interface{} `json:"position,omitempty"`
	RegionID int64 `json:"regionID,omitempty"`
	SolarSystemIDs []int64 `json:"solarSystemIDs,omitempty"`
	WormholeClassID int64 `json:"wormholeClassID,omitempty"`
}
