// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapRegions.jsonl

package types

// MapRegions represents the schema for mapRegions.jsonl
type MapRegions struct {
	Key int64 `json:"_key"`
	ConstellationIDs []int64 `json:"constellationIDs,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	FactionID int64 `json:"factionID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	NebulaID int64 `json:"nebulaID,omitempty"`
	Position map[string]interface{} `json:"position,omitempty"`
	WormholeClassID int64 `json:"wormholeClassID,omitempty"`
}
