// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapStars.jsonl

package types

// MapStars represents the schema for mapStars.jsonl
type MapStars struct {
	Key int64 `json:"_key,omitempty"`
	Radius int64 `json:"radius,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	Statistics map[string]interface{} `json:"statistics,omitempty"`
	TypeID int64 `json:"typeID,omitempty"`
}
