// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapPlanets.jsonl

package types

// MapPlanets represents the schema for mapPlanets.jsonl
type MapPlanets struct {
	Key int64 `json:"_key"`
	AsteroidBeltIDs []int64 `json:"asteroidBeltIDs,omitempty"`
	Attributes map[string]interface{} `json:"attributes"`
	CelestialIndex int64 `json:"celestialIndex"`
	MoonIDs []int64 `json:"moonIDs,omitempty"`
	NpcStationIDs []int64 `json:"npcStationIDs,omitempty"`
	OrbitID int64 `json:"orbitID"`
	Position map[string]interface{} `json:"position"`
	Radius int64 `json:"radius"`
	SolarSystemID int64 `json:"solarSystemID"`
	Statistics map[string]interface{} `json:"statistics"`
	TypeID int64 `json:"typeID"`
	UniqueName LocalizedText `json:"uniqueName,omitempty"`
}
