// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapPlanets.jsonl

package types

// MapPlanets represents the schema for mapPlanets.jsonl
type MapPlanets struct {
	Key int64 `json:"_key"`
	AsteroidBeltIDs []int64 `json:"asteroidBeltIDs,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	CelestialIndex int64 `json:"celestialIndex,omitempty"`
	MoonIDs []int64 `json:"moonIDs,omitempty"`
	NpcStationIDs []int64 `json:"npcStationIDs,omitempty"`
	OrbitID int64 `json:"orbitID,omitempty"`
	Position map[string]interface{} `json:"position,omitempty"`
	Radius int64 `json:"radius,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	Statistics map[string]interface{} `json:"statistics,omitempty"`
	TypeID int64 `json:"typeID,omitempty"`
}
