// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapStars.jsonl

package types

// MapStars represents the schema for mapStars.jsonl
type MapStars struct {
	Key int64 `json:"_key"`
	Radius int64 `json:"radius"`
	SolarSystemID int64 `json:"solarSystemID"`
	Statistics map[string]interface{} `json:"statistics"`
	TypeID int64 `json:"typeID"`
}
