// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapStargates.jsonl

package types

// MapStargates represents the schema for mapStargates.jsonl
type MapStargates struct {
	Key int64 `json:"_key,omitempty"`
	Destination map[string]interface{} `json:"destination,omitempty"`
	Position map[string]interface{} `json:"position,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	TypeID int64 `json:"typeID,omitempty"`
}
