// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapSecondarySuns.jsonl

package types

// MapSecondarySuns represents the schema for mapSecondarySuns.jsonl
type MapSecondarySuns struct {
	Key int64 `json:"_key"`
	EffectBeaconTypeID int64 `json:"effectBeaconTypeID"`
	Position map[string]interface{} `json:"position"`
	SolarSystemID int64 `json:"solarSystemID"`
	TypeID int64 `json:"typeID"`
}
