// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mapConstellations.jsonl

package types

// MapConstellations represents the schema for mapConstellations.jsonl
type MapConstellations struct {
	Key int64 `json:"_key"`
	FactionID int64 `json:"factionID,omitempty"`
	Name LocalizedText `json:"name"`
	Position map[string]interface{} `json:"position"`
	RegionID int64 `json:"regionID"`
	SolarSystemIDs []int64 `json:"solarSystemIDs"`
	WormholeClassID int64 `json:"wormholeClassID,omitempty"`
}
