// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: marketGroups.jsonl

package types

// MarketGroups represents the schema for marketGroups.jsonl
type MarketGroups struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description,omitempty"`
	HasTypes bool `json:"hasTypes,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	ParentGroupID int64 `json:"parentGroupID,omitempty"`
}
