// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: masteries.jsonl

package types

// Masteries represents the schema for masteries.jsonl
type Masteries struct {
	Key int64 `json:"_key,omitempty"`
	Value []map[string]interface{} `json:"_value,omitempty"`
}
