// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: mercenaryTacticalOperations.jsonl

package types

// MercenaryTacticalOperations represents the schema for mercenaryTacticalOperations.jsonl
type MercenaryTacticalOperations struct {
	Key int64 `json:"_key"`
	AnarchyImpact int64 `json:"anarchyImpact"`
	Description LocalizedText `json:"description"`
	DevelopmentImpact int64 `json:"developmentImpact"`
	DungeonID int64 `json:"dungeonID"`
	InfomorphBonus int64 `json:"infomorphBonus"`
	Name LocalizedText `json:"name"`
}
