// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: metaGroups.jsonl

package types

// MetaGroups represents the schema for metaGroups.jsonl
type MetaGroups struct {
	Key int64 `json:"_key,omitempty"`
	Color map[string]interface{} `json:"color,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	IconSuffix string `json:"iconSuffix,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
}
