// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: npcCorporations.jsonl

package types

// NpcCorporations represents the schema for npcCorporations.jsonl
type NpcCorporations struct {
	Key int64 `json:"_key"`
	AllowedMemberRaces []int64 `json:"allowedMemberRaces,omitempty"`
	CeoID int64 `json:"ceoID,omitempty"`
	CorporationTrades []map[string]interface{} `json:"corporationTrades,omitempty"`
	Deleted bool `json:"deleted,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	Divisions []map[string]interface{} `json:"divisions,omitempty"`
	EnemyID int64 `json:"enemyID,omitempty"`
	Extent string `json:"extent,omitempty"`
	FactionID int64 `json:"factionID,omitempty"`
	FriendID int64 `json:"friendID,omitempty"`
	HasPlayerPersonnelManager bool `json:"hasPlayerPersonnelManager,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	InitialPrice int64 `json:"initialPrice,omitempty"`
	Investors []map[string]interface{} `json:"investors,omitempty"`
	LpOfferTables []int64 `json:"lpOfferTables,omitempty"`
	MainActivityID int64 `json:"mainActivityID,omitempty"`
	MemberLimit int64 `json:"memberLimit,omitempty"`
	MinSecurity int64 `json:"minSecurity,omitempty"`
	MinimumJoinStanding int64 `json:"minimumJoinStanding,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	RaceID int64 `json:"raceID,omitempty"`
	SecondaryActivityID int64 `json:"secondaryActivityID,omitempty"`
	SendCharTerminationMessage bool `json:"sendCharTerminationMessage,omitempty"`
	Shares int64 `json:"shares,omitempty"`
	Size string `json:"size,omitempty"`
	SizeFactor float64 `json:"sizeFactor,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	StationID int64 `json:"stationID,omitempty"`
	TaxRate float64 `json:"taxRate,omitempty"`
	TickerName string `json:"tickerName,omitempty"`
	UniqueName bool `json:"uniqueName,omitempty"`
}
