// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: npcStations.jsonl

package types

// NpcStations represents the schema for npcStations.jsonl
type NpcStations struct {
	Key int64 `json:"_key"`
	CelestialIndex int64 `json:"celestialIndex,omitempty"`
	OperationID int64 `json:"operationID"`
	OrbitID int64 `json:"orbitID"`
	OrbitIndex int64 `json:"orbitIndex,omitempty"`
	OwnerID int64 `json:"ownerID"`
	Position map[string]interface{} `json:"position"`
	ReprocessingEfficiency float64 `json:"reprocessingEfficiency"`
	ReprocessingHangarFlag int64 `json:"reprocessingHangarFlag"`
	ReprocessingStationsTake float64 `json:"reprocessingStationsTake"`
	SolarSystemID int64 `json:"solarSystemID"`
	TypeID int64 `json:"typeID"`
	UseOperationName bool `json:"useOperationName"`
}
