// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: npcCharacters.jsonl

package types

// NpcCharacters represents the schema for npcCharacters.jsonl
type NpcCharacters struct {
	Key int64 `json:"_key,omitempty"`
	AncestryID int64 `json:"ancestryID,omitempty"`
	BloodlineID int64 `json:"bloodlineID,omitempty"`
	CareerID int64 `json:"careerID,omitempty"`
	CEO bool `json:"ceo,omitempty"`
	CorporationID int64 `json:"corporationID,omitempty"`
	Gender bool `json:"gender,omitempty"`
	LocationID int64 `json:"locationID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	RaceID int64 `json:"raceID,omitempty"`
	SchoolID int64 `json:"schoolID,omitempty"`
	Skills []map[string]interface{} `json:"skills,omitempty"`
	SpecialityID int64 `json:"specialityID,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	UniqueName bool `json:"uniqueName,omitempty"`
}
