// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: npcCorporationDivisions.jsonl

package types

// NpcCorporationDivisions represents the schema for npcCorporationDivisions.jsonl
type NpcCorporationDivisions struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	InternalName string `json:"internalName"`
	LeaderTypeName LocalizedText `json:"leaderTypeName"`
	Name LocalizedText `json:"name"`
}
