// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: npcCharacters.jsonl

package types

// NpcCharacters represents the schema for npcCharacters.jsonl
type NpcCharacters struct {
	Key int64 `json:"_key"`
	Agent map[string]interface{} `json:"agent,omitempty"`
	AncestryID int64 `json:"ancestryID,omitempty"`
	BloodlineID int64 `json:"bloodlineID"`
	CareerID int64 `json:"careerID,omitempty"`
	CEO bool `json:"ceo"`
	CorporationID int64 `json:"corporationID"`
	Description string `json:"description,omitempty"`
	Gender bool `json:"gender"`
	LocationID int64 `json:"locationID,omitempty"`
	Name LocalizedText `json:"name"`
	RaceID int64 `json:"raceID"`
	SchoolID int64 `json:"schoolID,omitempty"`
	Skills []map[string]interface{} `json:"skills,omitempty"`
	SpecialityID int64 `json:"specialityID,omitempty"`
	StartDate string `json:"startDate,omitempty"`
	UniqueName bool `json:"uniqueName"`
}
