// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: npcStations.jsonl

package types

// NpcStations represents the schema for npcStations.jsonl
type NpcStations struct {
	Key int64 `json:"_key,omitempty"`
	CelestialIndex int64 `json:"celestialIndex,omitempty"`
	OperationID int64 `json:"operationID,omitempty"`
	OrbitID int64 `json:"orbitID,omitempty"`
	OrbitIndex int64 `json:"orbitIndex,omitempty"`
	OwnerID int64 `json:"ownerID,omitempty"`
	Position map[string]interface{} `json:"position,omitempty"`
	ReprocessingEfficiency float64 `json:"reprocessingEfficiency,omitempty"`
	ReprocessingHangarFlag int64 `json:"reprocessingHangarFlag,omitempty"`
	ReprocessingStationsTake float64 `json:"reprocessingStationsTake,omitempty"`
	SolarSystemID int64 `json:"solarSystemID,omitempty"`
	TypeID int64 `json:"typeID,omitempty"`
	UseOperationName bool `json:"useOperationName,omitempty"`
}
