// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: planetResources.jsonl

package types

// PlanetResources represents the schema for planetResources.jsonl
type PlanetResources struct {
	Key int64 `json:"_key"`
	Power int64 `json:"power,omitempty"`
	Reagent map[string]interface{} `json:"reagent,omitempty"`
	Workforce int64 `json:"workforce,omitempty"`
}
