// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: planetSchematics.jsonl

package types

// PlanetSchematics represents the schema for planetSchematics.jsonl
type PlanetSchematics struct {
	Key int64 `json:"_key,omitempty"`
	CycleTime int64 `json:"cycleTime,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	Pins []int64 `json:"pins,omitempty"`
	Types []map[string]interface{} `json:"types,omitempty"`
}
