// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: planetResources.jsonl

package types

// PlanetResources represents the schema for planetResources.jsonl
type PlanetResources struct {
	Key int64 `json:"_key"`
	CycleMinutes int64 `json:"cycle_minutes,omitempty"`
	HarvestSiloMax int64 `json:"harvest_silo_max,omitempty"`
	MaturationCycleMinutes int64 `json:"maturation_cycle_minutes,omitempty"`
	MaturationPercent int64 `json:"maturation_percent,omitempty"`
	MatureSiloMax int64 `json:"mature_silo_max,omitempty"`
	Power int64 `json:"power,omitempty"`
	ReagentHarvestAmount int64 `json:"reagent_harvest_amount,omitempty"`
	ReagentTypeID int64 `json:"reagent_type_id,omitempty"`
	Workforce int64 `json:"workforce,omitempty"`
}
