// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: races.jsonl

package types

// Races represents the schema for races.jsonl
type Races struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	ShipTypeID int64 `json:"shipTypeID,omitempty"`
	Skills []map[string]interface{} `json:"skills,omitempty"`
}
