// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: _sde.jsonl

package types

// SDE represents the schema for _sde.jsonl
type SDE struct {
	Key string `json:"_key"`
	BuildNumber int64 `json:"buildNumber,omitempty"`
	ReleaseDate string `json:"releaseDate,omitempty"`
}
