// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: skinLicenses.jsonl

package types

// SkinLicenses represents the schema for skinLicenses.jsonl
type SkinLicenses struct {
	Key int64 `json:"_key"`
	Duration int64 `json:"duration"`
	IsSingleUse bool `json:"isSingleUse,omitempty"`
	LicenseTypeID int64 `json:"licenseTypeID"`
	SkinID int64 `json:"skinID"`
}
