// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: skins.jsonl

package types

// Skins represents the schema for skins.jsonl
type Skins struct {
	Key int64 `json:"_key,omitempty"`
	AllowCCPDevs bool `json:"allowCCPDevs,omitempty"`
	InternalName string `json:"internalName,omitempty"`
	IsStructureSkin bool `json:"isStructureSkin,omitempty"`
	SkinMaterialID int64 `json:"skinMaterialID,omitempty"`
	Types []int64 `json:"types,omitempty"`
	VisibleSerenity bool `json:"visibleSerenity,omitempty"`
	VisibleTranquility bool `json:"visibleTranquility,omitempty"`
}
