// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: skinMaterials.jsonl

package types

// SkinMaterials represents the schema for skinMaterials.jsonl
type SkinMaterials struct {
	Key int64 `json:"_key,omitempty"`
	DisplayName LocalizedText `json:"displayName,omitempty"`
	MaterialSetID int64 `json:"materialSetID,omitempty"`
}
