// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: skins.jsonl

package types

// Skins represents the schema for skins.jsonl
type Skins struct {
	Key int64 `json:"_key"`
	AllowCCPDevs bool `json:"allowCCPDevs"`
	InternalName string `json:"internalName"`
	IsStructureSkin bool `json:"isStructureSkin,omitempty"`
	SkinDescription LocalizedText `json:"skinDescription,omitempty"`
	SkinMaterialID int64 `json:"skinMaterialID"`
	Types []int64 `json:"types"`
	VisibleSerenity bool `json:"visibleSerenity"`
	VisibleTranquility bool `json:"visibleTranquility"`
}
