// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: sovereigntyUpgrades.jsonl

package types

// SovereigntyUpgrades represents the schema for sovereigntyUpgrades.jsonl
type SovereigntyUpgrades struct {
	Key int64 `json:"_key"`
	Fuel map[string]interface{} `json:"fuel,omitempty"`
	MutuallyExclusiveGroup string `json:"mutually_exclusive_group"`
	PowerAllocation int64 `json:"power_allocation,omitempty"`
	PowerProduction int64 `json:"power_production,omitempty"`
	WorkforceAllocation int64 `json:"workforce_allocation,omitempty"`
	WorkforceProduction int64 `json:"workforce_production,omitempty"`
}
