// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: sovereigntyUpgrades.jsonl

package types

// SovereigntyUpgrades represents the schema for sovereigntyUpgrades.jsonl
type SovereigntyUpgrades struct {
	Key int64 `json:"_key,omitempty"`
	FuelHourlyUpkeep int64 `json:"fuel_hourly_upkeep,omitempty"`
	FuelStartupCost int64 `json:"fuel_startup_cost,omitempty"`
	FuelTypeID int64 `json:"fuel_type_id,omitempty"`
	MutuallyExclusiveGroup string `json:"mutually_exclusive_group,omitempty"`
	PowerAllocation int64 `json:"power_allocation,omitempty"`
	WorkforceAllocation int64 `json:"workforce_allocation,omitempty"`
}
