// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: stationServices.jsonl

package types

// StationServices represents the schema for stationServices.jsonl
type StationServices struct {
	Key int64 `json:"_key"`
	Description LocalizedText `json:"description,omitempty"`
	ServiceName LocalizedText `json:"serviceName,omitempty"`
}
