// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: stationOperations.jsonl

package types

// StationOperations represents the schema for stationOperations.jsonl
type StationOperations struct {
	Key int64 `json:"_key"`
	ActivityID int64 `json:"activityID"`
	Border float64 `json:"border"`
	Corridor float64 `json:"corridor"`
	Description LocalizedText `json:"description,omitempty"`
	Fringe float64 `json:"fringe"`
	Hub float64 `json:"hub"`
	ManufacturingFactor float64 `json:"manufacturingFactor"`
	OperationName LocalizedText `json:"operationName"`
	Ratio float64 `json:"ratio"`
	ResearchFactor float64 `json:"researchFactor"`
	Services []int64 `json:"services"`
	StationTypes []map[string]interface{} `json:"stationTypes,omitempty"`
}
