// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: stationOperations.jsonl

package types

// StationOperations represents the schema for stationOperations.jsonl
type StationOperations struct {
	Key int64 `json:"_key,omitempty"`
	ActivityID int64 `json:"activityID,omitempty"`
	Border interface{} `json:"border,omitempty"`
	Corridor interface{} `json:"corridor,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	Fringe interface{} `json:"fringe,omitempty"`
	Hub interface{} `json:"hub,omitempty"`
	ManufacturingFactor interface{} `json:"manufacturingFactor,omitempty"`
	OperationName LocalizedText `json:"operationName,omitempty"`
	Ratio interface{} `json:"ratio,omitempty"`
	ResearchFactor interface{} `json:"researchFactor,omitempty"`
	Services []int64 `json:"services,omitempty"`
	StationTypes []map[string]interface{} `json:"stationTypes,omitempty"`
}
