// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: translationLanguages.jsonl

package types

// TranslationLanguages represents the schema for translationLanguages.jsonl
type TranslationLanguages struct {
	Key string `json:"_key"`
	Name string `json:"name,omitempty"`
}
