// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: typeLists.jsonl

package types

// TypeLists represents the schema for typeLists.jsonl
type TypeLists struct {
	Key int64 `json:"_key"`
	DisplayDescription LocalizedText `json:"displayDescription,omitempty"`
	DisplayName LocalizedText `json:"displayName,omitempty"`
	ExcludedCategoryIDs []int64 `json:"excludedCategoryIDs,omitempty"`
	ExcludedGroupIDs []int64 `json:"excludedGroupIDs,omitempty"`
	ExcludedTypeIDs []int64 `json:"excludedTypeIDs,omitempty"`
	IncludedCategoryIDs []int64 `json:"includedCategoryIDs,omitempty"`
	IncludedGroupIDs []int64 `json:"includedGroupIDs,omitempty"`
	IncludedTypeIDs []int64 `json:"includedTypeIDs,omitempty"`
	Name string `json:"name"`
}
