// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: typeMaterials.jsonl

package types

// TypeMaterials represents the schema for typeMaterials.jsonl
type TypeMaterials struct {
	Key int64 `json:"_key"`
	Materials []map[string]interface{} `json:"materials,omitempty"`
}
