// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: typeBonus.jsonl

package types

// TypeBonus represents the schema for typeBonus.jsonl
type TypeBonus struct {
	Key int64 `json:"_key"`
	IconID int64 `json:"iconID,omitempty"`
	MiscBonuses []map[string]interface{} `json:"miscBonuses,omitempty"`
	RoleBonuses []map[string]interface{} `json:"roleBonuses,omitempty"`
	Types []map[string]interface{} `json:"types,omitempty"`
}
