// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: types.jsonl

package types

// Types represents the schema for types.jsonl
type Types struct {
	Key int64 `json:"_key"`
	BasePrice int64 `json:"basePrice,omitempty"`
	Capacity int64 `json:"capacity,omitempty"`
	Description LocalizedText `json:"description,omitempty"`
	GraphicID int64 `json:"graphicID,omitempty"`
	GroupID int64 `json:"groupID,omitempty"`
	IconID int64 `json:"iconID,omitempty"`
	MarketGroupID int64 `json:"marketGroupID,omitempty"`
	Mass float64 `json:"mass,omitempty"`
	MetaGroupID int64 `json:"metaGroupID,omitempty"`
	Name LocalizedText `json:"name,omitempty"`
	PortionSize int64 `json:"portionSize,omitempty"`
	Published bool `json:"published,omitempty"`
	RaceID int64 `json:"raceID,omitempty"`
	Radius int64 `json:"radius,omitempty"`
	SoundID int64 `json:"soundID,omitempty"`
	Volume float64 `json:"volume,omitempty"`
}
