// Code generated by sde-schema-gen from JSONL data analysis
// DO NOT EDIT manually - regenerate with: sde-schema-gen
// Source: typeDogma.jsonl

package types

// TypeDogma represents the schema for typeDogma.jsonl
type TypeDogma struct {
	Key int64 `json:"_key,omitempty"`
	DogmaAttributes []map[string]interface{} `json:"dogmaAttributes,omitempty"`
	DogmaEffects []map[string]interface{} `json:"dogmaEffects,omitempty"`
}
