// Code generated by sde-schema-gen. DO NOT EDIT.

package registry

// Mappings is the generated registry of all JSONL datasets to import.
// Dieser Platzhalter wird beim ersten sde-schema-gen-Lauf überschrieben.
var Mappings = []SchemaMapping{}
